server:
  port: 8989
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      encoding: utf-8

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: false
  web:
    resources:
      add-mappings: false
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: kr.co.kcp.backendcoding
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true

logging:
  level:
    root: INFO
